module.exports = {
  'hs:network': '192.168.0.1/24',
  'hs:hostDetection:cron': '*/30 * * * * *',
  'hs:osDetection:auto': true,
  'hs:versionDetection:auto': true,

  'ids:vars:address-groups': {
    'HOME_NET': '[192.168.0.0/24]',
    'EXTERNAL_NET': '!$HOME_NET',
    'HTTP_SERVERS': '$HOME_NET',
    'SMTP_SERVERS': '$HOME_NET',
    'SQL_SERVERS': '$HOME_NET',
    'DNS_SERVERS': '$HOME_NET',
    'TELNET_SERVERS': '$HOME_NET',
    'AIM_SERVERS': '$EXTERNAL_NET',
    'DNP3_SERVER': '$HOME_NET',
    'DNP3_CLIENT': '$HOME_NET',
    'MODBUS_CLIENT': '$HOME_NET',
    'MODBUS_SERVER': '$HOME_NET',
    'ENIP_CLIENT': '$HOME_NET',
    'ENIP_SERVER': '$HOME_NET'
  },
  'ids:vars:port-groups': {
    'HTTP_PORTS': '80',
    'SHELLCODE_PORTS': '!80',
    'ORACLE_PORTS': 1521,
    'SSH_PORTS': 22,
    'DNP3_PORTS': 20000,
    'MODBUS_PORTS': 502
  }
  ,
  'ids:enable-rules': [
    // 'botcc.rules',
    // 'ciarmy.rules',
    // 'compromised.rules',
    // 'drop.rules',
    // 'dshield.rules',
    'emerging-attack_response.rules',
    'emerging-chat.rules',
    'emerging-current_events.rules',
    'emerging-dns.rules',
    'emerging-dos.rules',
    'emerging-exploit.rules',
    'emerging-ftp.rules',
    'emerging-imap.rules',
    'emerging-malware.rules',
    'emerging-misc.rules',
    'emerging-mobile_malware.rules',
    'emerging-netbios.rules',
    'emerging-p2p.rules',
    'emerging-policy.rules',
    'emerging-pop3.rules',
    'emerging-rpc.rules',
    'emerging-scan.rules',
    'emerging-smtp.rules',
    'emerging-snmp.rules',
    'emerging-sql.rules',
    'emerging-telnet.rules',
    'emerging-tftp.rules',
    'emerging-trojan.rules',
    'emerging-user_agents.rules',
    'emerging-voip.rules',
    'emerging-web_client.rules',
    'emerging-web_server.rules',
    'emerging-worm.rules',
    'tor.rules',
    'http-events.rules',
    'smtp-events.rules',
    'dns-events.rules',
    'tls-events.rules'
  ]
};
