vars:
  address-groups:
    HOME_NET: '[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]'
    EXTERNAL_NET: '!$HOME_NET'
    HTTP_SERVERS: $HOME_NET
    SMTP_SERVERS: $HOME_NET
    SQL_SERVERS: $HOME_NET
    DNS_SERVERS: $HOME_NET
    TELNET_SERVERS: $HOME_NET
    AIM_SERVERS: $EXTERNAL_NET
    DNP3_SERVER: $HOME_NET
    DNP3_CLIENT: $HOME_NET
    MODBUS_CLIENT: $HOME_NET
    MODBUS_SERVER: $HOME_NET
    ENIP_CLIENT: $HOME_NET
    ENIP_SERVER: $HOME_NET
  port-groups:
    HTTP_PORTS: '80'
    SHELLCODE_PORTS: '!80'
    ORACLE_PORTS: 1521
    SSH_PORTS: 22
    DNP3_PORTS: 20000
    MODBUS_PORTS: 502
default-rule-path: /etc/suricata/rules
rule-files:
  - botcc.rules
  - ciarmy.rules
  - compromised.rules
  - drop.rules
  - dshield.rules
  - emerging-attack_response.rules
  - emerging-chat.rules
  - emerging-current_events.rules
  - emerging-dns.rules
  - emerging-dos.rules
  - emerging-exploit.rules
  - emerging-ftp.rules
  - emerging-imap.rules
  - emerging-malware.rules
  - emerging-misc.rules
  - emerging-mobile_malware.rules
  - emerging-netbios.rules
  - emerging-p2p.rules
  - emerging-policy.rules
  - emerging-pop3.rules
  - emerging-rpc.rules
  - emerging-scan.rules
  - emerging-smtp.rules
  - emerging-snmp.rules
  - emerging-sql.rules
  - emerging-telnet.rules
  - emerging-tftp.rules
  - emerging-trojan.rules
  - emerging-user_agents.rules
  - emerging-voip.rules
  - emerging-web_client.rules
  - emerging-web_server.rules
  - emerging-worm.rules
  - tor.rules
  - http-events.rules
  - smtp-events.rules
  - dns-events.rules
  - tls-events.rules
classification-file: /etc/suricata/classification.config
reference-config-file: /etc/suricata/reference.config
default-log-dir: /home/kurefm/Codes/personal/js/bismuth/src/suricata
stats:
  enabled: 'yes'
  interval: 8
outputs:
  - fast:
      enabled: 'yes'
      filename: fast.log
      append: 'yes'
  - eve-log:
      enabled: 'no'
      filetype: regular
      filename: eve.json
      types:
        - alert:
            http: 'yes'
            tls: 'yes'
            ssh: 'yes'
            smtp: 'yes'
            dnp3: 'yes'
            tagged-packets: 'yes'
            xff:
              enabled: 'no'
              mode: extra-data
              deployment: reverse
              header: X-Forwarded-For
        - http:
            extended: 'yes'
        - dns:
            query: 'yes'
            answer: 'yes'
        - tls:
            extended: 'yes'
        - files:
            force-magic: 'no'
        - smtp: null
        - ssh
        - stats:
            totals: 'yes'
            threads: 'no'
            deltas: 'no'
        - flow
  - unified2-alert:
      enabled: 'no'
      filename: unified2.alert
      xff:
        enabled: 'no'
        mode: extra-data
        deployment: reverse
        header: X-Forwarded-For
  - http-log:
      enabled: 'no'
      filename: http.log
      append: 'yes'
  - tls-log:
      enabled: 'no'
      filename: tls.log
      append: 'yes'
  - tls-store:
      enabled: 'no'
  - dns-log:
      enabled: 'no'
      filename: dns.log
      append: 'yes'
  - pcap-log:
      enabled: 'no'
      filename: log.pcap
      limit: 1000mb
      max-files: 2000
      mode: normal
      use-stream-depth: 'no'
      honor-pass-rules: 'no'
  - alert-debug:
      enabled: 'no'
      filename: alert-debug.log
      append: 'yes'
  - alert-prelude:
      enabled: 'no'
      profile: suricata
      log-packet-content: 'no'
      log-packet-header: 'yes'
  - stats:
      enabled: 'yes'
      filename: stats.log
      totals: 'yes'
      threads: 'no'
  - syslog:
      enabled: 'no'
      facility: local5
  - drop:
      enabled: 'no'
      filename: drop.log
      append: 'yes'
  - file-store:
      enabled: 'no'
      log-dir: files
      force-magic: 'no'
      force-filestore: 'no'
  - file-log:
      enabled: 'no'
      filename: files-json.log
      append: 'yes'
      force-magic: 'no'
  - tcp-data:
      enabled: 'no'
      type: file
      filename: tcp-data.log
  - http-body-data:
      enabled: 'no'
      type: file
      filename: http-data.log
  - lua:
      enabled: 'no'
      scripts: null
logging:
  default-log-level: notice
  default-output-filter: null
  outputs:
    - console:
        enabled: 'yes'
    - file:
        enabled: 'yes'
        level: info
        filename: /var/log/suricata/suricata.log
    - syslog:
        enabled: 'no'
        facility: local5
        format: '[%i] <%d> -- '
af-packet:
  - interface: eth0
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: 'yes'
  - interface: default
pcap:
  - interface: eth0
  - interface: default
pcap-file:
  checksum-checks: auto
app-layer:
  protocols:
    tls:
      enabled: 'yes'
      detection-ports:
        dp: 443
    dcerpc:
      enabled: 'yes'
    ftp:
      enabled: 'yes'
    ssh:
      enabled: 'yes'
    smtp:
      enabled: 'yes'
      mime:
        decode-mime: 'yes'
        decode-base64: 'yes'
        decode-quoted-printable: 'yes'
        header-value-depth: 2000
        extract-urls: 'yes'
        body-md5: 'no'
      inspected-tracker:
        content-limit: 100000
        content-inspect-min-size: 32768
        content-inspect-window: 4096
    imap:
      enabled: detection-only
    msn:
      enabled: detection-only
    smb:
      enabled: 'yes'
      detection-ports:
        dp: '139, 445'
    dns:
      tcp:
        enabled: 'yes'
        detection-ports:
          dp: 53
      udp:
        enabled: 'yes'
        detection-ports:
          dp: 53
    http:
      enabled: 'yes'
      libhtp:
        default-config:
          personality: IDS
          request-body-limit: 100kb
          response-body-limit: 100kb
          request-body-minimal-inspect-size: 32kb
          request-body-inspect-window: 4kb
          response-body-minimal-inspect-size: 40kb
          response-body-inspect-window: 16kb
          response-body-decompress-layer-limit: 2
          http-body-inline: auto
          double-decode-path: 'no'
          double-decode-query: 'no'
        server-config: null
    modbus:
      enabled: 'no'
      detection-ports:
        dp: 502
      stream-depth: 0
    dnp3:
      enabled: 'no'
      detection-ports:
        dp: 20000
    enip:
      enabled: 'no'
      detection-ports:
        dp: 44818
        sp: 44818
asn1-max-frames: 256
coredump:
  max-dump: unlimited
host-mode: auto
unix-command:
  enabled: auto
legacy:
  uricontent: enabled
engine-analysis:
  rules-fast-pattern: 'yes'
  rules: 'yes'
pcre:
  match-limit: 3500
  match-limit-recursion: 1500
host-os-policy:
  windows:
    - 0.0.0.0/0
  bsd: []
  bsd-right: []
  old-linux: []
  linux: []
  old-solaris: []
  solaris: []
  hpux10: []
  hpux11: []
  irix: []
  macos: []
  vista: []
  windows2k3: []
defrag:
  memcap: 32mb
  hash-size: 65536
  trackers: 65535
  max-frags: 65535
  prealloc: 'yes'
  timeout: 60
flow:
  memcap: 128mb
  hash-size: 65536
  prealloc: 10000
  emergency-recovery: 30
vlan:
  use-for-tracking: true
flow-timeouts:
  default:
    new: 30
    established: 300
    closed: 0
    bypassed: 100
    emergency-new: 10
    emergency-established: 100
    emergency-closed: 0
    emergency-bypassed: 50
  tcp:
    new: 60
    established: 600
    closed: 60
    bypassed: 100
    emergency-new: 5
    emergency-established: 100
    emergency-closed: 10
    emergency-bypassed: 50
  udp:
    new: 30
    established: 300
    bypassed: 100
    emergency-new: 10
    emergency-established: 100
    emergency-bypassed: 50
  icmp:
    new: 30
    established: 300
    bypassed: 100
    emergency-new: 10
    emergency-established: 100
    emergency-bypassed: 50
stream:
  memcap: 64mb
  checksum-validation: 'yes'
  inline: auto
  reassembly:
    memcap: 256mb
    depth: 1mb
    toserver-chunk-size: 2560
    toclient-chunk-size: 2560
    randomize-chunk-size: 'yes'
host:
  hash-size: 4096
  prealloc: 1000
  memcap: 32mb
detect:
  profile: medium
  custom-values:
    toclient-groups: 3
    toserver-groups: 25
  sgh-mpm-context: auto
  inspection-recursion-limit: 3000
  prefilter:
    default: mpm
  grouping: null
  profiling:
    grouping:
      dump-to-disk: false
      include-rules: false
      include-mpm-stats: false
mpm-algo: auto
spm-algo: auto
threading:
  set-cpu-affinity: 'no'
  cpu-affinity:
    - management-cpu-set:
        cpu:
          - 0
    - receive-cpu-set:
        cpu:
          - 0
    - worker-cpu-set:
        cpu:
          - all
        mode: exclusive
        prio:
          low:
            - 0
          medium:
            - 1-2
          high:
            - 3
          default: medium
  detect-thread-ratio: 1
luajit:
  states: 128
profiling:
  rules:
    enabled: 'yes'
    filename: rule_perf.log
    append: 'yes'
    sort: avgticks
    limit: 100
    json: 'no'
  keywords:
    enabled: 'yes'
    filename: keyword_perf.log
    append: 'yes'
  rulegroups:
    enabled: 'yes'
    filename: rule_group_perf.log
    append: 'yes'
  packets:
    enabled: 'yes'
    filename: packet_stats.log
    append: 'yes'
    csv:
      enabled: 'no'
      filename: packet_stats.csv
  locks:
    enabled: 'no'
    filename: lock_stats.log
    append: 'yes'
  pcap-log:
    enabled: 'no'
    filename: pcaplog_stats.log
    append: 'yes'
nfq: null
nflog:
  - group: 2
    buffer-size: 18432
  - group: default
    qthreshold: 1
    qtimeout: 100
    max-size: 20000
capture: null
netmap:
  - interface: eth2
  - interface: default
pfring:
  - interface: eth0
    threads: 1
    cluster-id: 99
    cluster-type: cluster_flow
  - interface: default
ipfw: null
napatech:
  hba: -1
  use-all-streams: 'yes'
  streams:
    - 1
    - 2
    - 3
mpipe:
  load-balance: dynamic
  iqueue-packets: 2048
  inputs:
    - interface: xgbe2
    - interface: xgbe3
    - interface: xgbe4
  stack:
    size128: 0
    size256: 9
    size512: 0
    size1024: 0
    size1664: 7
    size4096: 0
    size10386: 0
    size16384: 0
cuda:
  mpm:
    data-buffer-size-min-limit: 0
    data-buffer-size-max-limit: 1500
    cudabuffer-buffer-size: 500mb
    gpu-transfer-size: 50mb
    batching-timeout: 2000
    device-id: 0
    cuda-streams: 2
