elasticsearch:
  image: bismuth/elasticsearch:0.1.0
  ports:
    - 9200:9200
    - 9300:9300

node:
  image: bismuth:0.1.0
  environment:
    ELASTICSEARCH_URL: http://localhost:9200
    NODE_ENV: production
  net: host
