winston:
  logger:
    console:
      level: info
      colorize: all
    dailyRotateFile:
      level: info
      filename: ./log/bismuth
      datePattern: .yyyy-MM-dd.log
      maxsize: 10000000
      maxFiles: 30
      zippedArchive: true
  labels:
    - Node
    - HS-Agent
    - IDS-Agent
